# Generated by Django 4.0.2 on 2022-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('article_tag', models.CharField(max_length=50)),
                ('article_title', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
